# Pandas

In [4]:
# instalar
!pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python3 -m pip install --upgrade pip

In [5]:
# instalar
import pandas as pd

# lista
# Diccionar

data = [['Juan', 25], ['Pedro', 25], ['Luis', 25]]

print(data)

df = pd.DataFrame(data, columns = ['Nombre', 'Edad'])
df

[['Juan', 25], ['Pedro', 25], ['Luis', 25]]

  Nombre  Edad
0   Juan    25
1  Pedro    25
2   Luis    25

In [6]:
# Crear desde Diccionario
data = {
    'Nombre': ['Juan', 'Pedro', 'Luis'],
    'Edad': [25, 26, 25]
}

df_1 = pd.DataFrame(data)

df_1

  Nombre  Edad
0   Juan    25
1  Pedro    26
2   Luis    25

In [7]:
# Leer un archivo de una ruta indicada
df = pd.read_csv('utils/data/data.csv')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [8]:
# Leer un archivo sin extension y con un separador especial
df = pd.read_csv('utils/data/data', sep = '|')
df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [9]:
# Leer un archivo csv sin cabecera
df = pd.read_csv('utils/data/data_without_header',
                 sep = ',',
                 header= None,
                 names = ['Nombre', 'Edad', 'Ciudad']
                 )

df

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [10]:
# leer un archivo json

df = pd.read_json('utils/data/data.json')

df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

## metodos con dataframe

In [11]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [12]:
df.describe()

       edad
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [13]:
df.head()

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [14]:
df.tail(2)

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [15]:
df.columns

Index(['nombre', 'edad', 'ciudad'], dtype='str')

In [16]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [17]:
df.count()

nombre    3
edad      3
ciudad    3
dtype: int64

## Acceder a los Valores

In [18]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [19]:
df['ciudad']

#df[['ciudad', 'edad']]

0       Madrid
1    Barcelona
2      Sevilla
Name: ciudad, dtype: str

In [20]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [21]:
# Seleccionar una fila

print(df.loc[0])

# Multiples Lineas
print("### \n")
print(df.loc[[0, 2]])

# Filas que cumplie cierta condicion
print("### \n")
print(df[df['edad']>29])

nombre      Juan
edad          25
ciudad    Madrid
Name: 0, dtype: object
###

  nombre  edad   ciudad
0   Juan    25   Madrid
2  Pedro    35  Sevilla
###

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

## Acceder a API

In [22]:
import pandas as pd
import requests

url = "https://api.open-meteo.com/v1/forecast"

params = {
    "latitude": -12.04,
    "longitude": -77.04,
    "hourly": "temperature_2m",
    "timezone": "America/Lima",
}

data = requests.get(url, params= params).json() # Pedir la data

df = pd.DataFrame(data) # Convertir

df.head() # usar

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,hourly_units,hourly
time,-12.056238,-77.06198,0.034213,-18000,America/Lima,GMT-5,133.0,iso8601,"[2026-09-08T00:00, 2026-09-08T01:00, 2026-09-0..."
temperature_2m,-12.056238,-77.06198,0.034213,-18000,America/Lima,GMT-5,133.0,°C,"[21.3, 21.6, 21.1, 21.0, 20.7, 20.5, 20.6, 21...."

In [23]:
url = "https://www.alphavantage.co/query"

params = {
    "function": "TIME_SERIES_DAILY",
    "symbol": "IBM",
    "apikey": "demo",        # reemplazar por tu clave
}

data = requests.get(url, params=params).json()
df = pd.DataFrame(data["Time Series (Daily)"]).T

df.head()

             1. open   2. high    3. low  4. close 5. volume
2026-09-08  232.9500  233.4000  230.2000  232.0900   4536420
2026-09-04  233.3300  236.1700  231.6800  234.8900   3722860
2026-09-03  234.3800  238.2900  232.8150  234.7100   4375426
2026-09-02  230.5450  232.8800  229.1000  231.7000   4654576
2026-09-01  231.0000  233.0900  229.9000  231.4000   3240341